---
# - name: start tarantool
#   command: tarantoolctl start {{ name }}-ycsb
#   sudo: true
- name: start Tarantool
  command: './tarantool tarantool.lua'
  args:
    chdir: '{{ path }}/{{ name }}'
...
