---
- hosts: dbservers
  gather_facts: no
  sudo: True
  roles:
    - tarantool/prepare
    - redis/prepare
    - { role: memcached,         prepare: True}
- hosts: ycsbservers
  gather_facts: no
  roles:
    - ycsb/prepare
...
