---
- name: add tarantool repo key
  apt_key:
  args:
    url: 'http://tarantool.org/dist/public.key'
    state: present
- name: add repositories
  apt_repository:
  args:
    repo: 'deb http://tarantool.org/dist/master/ubuntu/ trusty main'
    state: present
    update_cache: yes
- name: install packages
  apt: name={{ item }}
  with_items:
    - tarantool
    - tarantool-common
  args:
    state: latest
...
