---
- name: copy tarantool config
  template: src={{ name }}.lua.j2
            dest=/etc/tarantool/instances.enabled/{{ name }}-ycsb.lua
            mode=0755
            owner=root
            group=root
  sudo: true
...
