---
- name: add repository
  apt_repository: repo='ppa:chris-lea/redis-server' state=present
- name: update
  apt:  update_cache=yes
- name: install packages
  apt:  name={{ item }}
  with_items:
    - redis-server
    - redis-tools
- name: create directories
  shell: mkdir -p {{ item }}
  with_items:
    - /etc/redis
    - /var/log/redis
    - /var/run/redis
- name: stop dbs
  service: name=redis-server state=stopped
...
