---
# - name: stop tarantool
#   command: tarantoolctl stop {{ name }}-ycsb
#   sudo: true
# - name: stop Tarantool
#   shell: 'kill `cat {{ db }}.pid`'
#   args:
#     chdir: '{{ path }}/{{ name }}'
- name: stop tarantool
  command: './{{ binary }} {{ tarantoolctl }} stop {{ config }} chdir={{ path }}'
  environment:
    PWD: '{{ path }}'
...
