---
- name: copy memcached config/init
  template: "src={{ item.src }}
             dest={{ item.dest }}
             mode=755
             owner=root
             group=root"
  with_items:
    - src: "{{ name }}.conf.j2"
      dest: "/etc/memcached/{{ name }}_{{ port }}.conf"
    - src: "{{ name }}.init.j2"
      dest: "/etc/init.d/{{ name }}_{{ port }}"
  sudo: true
...
