---
- include: cleanup.yml
- name: remove config and init
  shell: "rm -f {{ item }}"
  with_items:
    - "/etc/init.d/{{ name }}_{{ port }}"
    - "/etc/memcached/{{ name }}_{{ port }}.conf"
  sudo: true
...
